apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{ include "pwa.app" . | indent 4 }}
data:
  myValues: "Hello world"
  {{- $releaseName := .Release.Name -}}
  {{- range $key, $value := .Values.favorite }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  release: {{ $releaseName }}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{ $index }}: {{ $topping }}
    {{- end }}
{{ include "pwa.app" . | indent 2 }}