import './global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="bg-blue-300 p-2">Header</header>
        <div className="flex-grow">{children}</div>
        <footer className="bg-orange-300 p-2">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
