apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: bitnami/jenkins:latest
          env:
            - name: JENKINS_USERNAME
              value: test
          ports:
            - name: http
              containerPort: 8080
