language: node_js
node_js: 10

cache:
  yarn: true
sudo: required
dist: trusty

stages:
  - Tests
  - name: Release
    if: branch = v2 and type = push

jobs:
  fail_fast: true
  include:
    - stage: Tests
      name: Conventional Commits
      node_js: 10
      script:
        - commitlint-travis
    - name: Fixed Dependencies
    - name: Floating Dependencies
      install: yarn install --no-lockfile --non-interactive
    - node_js: 8
    - node_js: stable

    - stage: Release
      name: Github Release
      script: yarn semantic-release

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - lerna run test --scope=hello-ts
