apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.service.NodePort }}
  selector:
    app: jenkins
