const EARTH_RADIUS_IN_MILE = 3963.2;
const EARTH_RADIUS_IN_KM = 6378.1;
const ONE_METER_IN_KM = 0.001;
const ONE_METER_IN_MI = 0.000621371;

module.exports = {
  EARTH_RADIUS_IN_KM,
  EARTH_RADIUS_IN_MILE,
  ONE_METER_IN_KM,
  ONE_METER_IN_MI,
};
