const ERROR_MONGO_CAST_ERROR = 'CastError';
const ERROR_MONGO_DUPLICATE_FIELD = 11000;
const ERROR_MONGO_VALIDATION_ERROR = 'ValidationError';

module.exports = {
  ERROR_MONGO_CAST_ERROR,
  ERROR_MONGO_DUPLICATE_FIELD,
  ERROR_MONGO_VALIDATION_ERROR,
};
